app/views/login.py
# coding=utf-8

from flask import Blueprint, request, session, render_template, redirect, url_for
import MongoDBDao.UserDao
import sys
reload(sys)
sys.setdefaultencoding('utf8')

login = Blueprint('login', __name__)


@login.route('/')
def index():
    return redirect(url_for('login.go_login'))


@login.route('/go_login')
def go_login():
    return render_template('login.html')


@login.route('/do_login', methods=['POST'])
def do_login():
    username = request.form['username']
    password = request.form['password']

    # 查询用户名密码
    user = MongoDBDao.UserDao.find_user(username)
    if user is None:
        error = 'User Not Exist'
        return render_template('login.html', error=error)

    print(user)
    print(user['password'])
    if user['password'] != password:
        error = '密码不正确'
        return render_template('login.html', error=error)

    # 把user_id存到session
    session['user_id'] = user['user_id']

    # 跳转到我的首页
    return redirect(url_for('mine.mine_index'))


@login.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('login.go_login'))

app/views/mine.py
# coding=utf-8

import os
from flask import Blueprint, request, session, render_template, redirect, url_for, json, make_response
from werkzeug.utils import secure_filename
from MongoDBDao import DiaryDao, IDDao, DiaryPasswordDao, PersonalSignDao, DiaryStatisticDao
import sys, time
import re
from uploader import Uploader

reload(sys)
sys.setdefaultencoding('utf8')

mine = Blueprint('mine', __name__, static_folder='../static')

default_page_size = 1000

UPLOAD_FOLDER = '/Users/jinweihe/Desktop/tmpFileUpload'


@mine.route('/mine/choose_by_type/<type>')
def choose_by_type(type):
    #count = DiaryDao.find_diaries_count_by_type(user_id, type)
    user_id = session['user_id']
    diaries = DiaryDao.find_diaries_by_type(user_id, type, 1, default_page_size)
    return render_template('mine.html', diaries=diaries, user_id=user_id, select_type=type)


@mine.route('/mine/view_diary/<diary_id>')
def view_diary(diary_id):
    diary = DiaryDao.find_diary_by_id(int(diary_id))

    diary_password = ''
    if diary['private'] == '2':
        diary_password_obj = DiaryPasswordDao.find_by_diary_id(diary['id'])
        diary_password = diary_password_obj['diary_password']

    DiaryStatisticDao.insert_or_update_view_number(int(diary_id), session['user_id'])
    return render_template('view_diary.html', user_id=session['user_id'], diary=diary, view_or_edit=1, diary_password=diary_password)


@mine.route('/mine/go_edit_diary/<diary_id>')
def go_edit_diary(diary_id):
    diary = DiaryDao.find_diary_by_id(int(diary_id))

    diary_password = ''
    if diary['private'] == '2':
        diary_password_obj = DiaryPasswordDao.find_by_diary_id(int(diary['id']))
        diary_password = diary_password_obj['diary_password']

    return render_template('view_diary.html', user_id=session['user_id'], diary=diary, view_or_edit=2, diary_password=diary_password)


@mine.route('/mine/edit_diary/<diary_id>', methods=['post'])
def edit_diary(diary_id):
    session_user_id = session['user_id']
    diary = DiaryDao.find_diary_by_id(int(diary_id))
    owner_id = diary['user_id']
    if str(owner_id) != str(session_user_id):
        return 'error'

    title = request.form['title']
    type = request.form['type']
    weather = request.form['weather']
    content = request.form['content']

    private = request.form['private']
    if private == '2':
        diary_password = request.form['diary_password']
        DiaryPasswordDao.insert_or_update(int(diary_id), diary_password)

    DiaryDao.update_diary_id(int(diary_id), title, weather, type, diary['date'], content, private)
    return 'ok'


@mine.route('/mine/go_write_diary/<user_id>')
def go_write_diary(user_id):
    return render_template('write_diary.html', user_id=user_id)


@mine.route('/mine/delete_diary/<diary_id>')
def delete_diary(diary_id):
    DiaryDao.delete_diary_by_id(diary_id)
    return None


@mine.route('/mine/personal_sign/edit')
def personal_sign():
    # 查询个性签名
    user_id = session['user_id']
    personal_sign_record = PersonalSignDao.find_personal_sign_by_user_id(user_id)
    sign_content = ''
    if personal_sign_record is not None:
        sign_content = personal_sign_record['sign_content']

    return render_template('personal_sign.html', sign_content=sign_content)


@mine.route('/mine/personal_sign/save', methods=['post'])
def save_personal_sign():
    user_id = session['user_id']
    sign_content = request.form['sign_content']
    PersonalSignDao.save_or_update_personal_sign(user_id, sign_content)
    return 'ok'


@mine.route('/mine/save_diary', methods=['post'])
def save_diary():

    ##验证用户
    user_id = request.form['user_id']
    session_user_id = session['user_id']
    if str(user_id) != str(session_user_id):
        return 'error'

    title = request.form['title']
    type = request.form['type']
    weather = request.form['weather']
    content = request.form['content']

    diary_id = IDDao.find_and_modify('diary')
    date = time.strftime('%Y年%m月%d日', time.localtime(time.time()))

    private = request.form['private']
    if private == '2':
        diary_password = request.form['diary_password']
        DiaryPasswordDao.insert_or_update(diary_id['id'], diary_password)

    DiaryDao.insert_one_diary(diary_id['id'], int(user_id), title, weather, type, date, content, private)

    return 'ok'


@mine.route('/mine/list')
def mine_index():
    user_id=session['user_id']
    #count = DiaryDao.find_diaries_count(user_id)
    diaries = DiaryDao.find_diaries(user_id, 1, default_page_size)
    return render_template('mine.html', diaries=diaries, user_id=user_id, select_type='0')


@mine.route('/upload', methods=['GET', 'POST'])
def upload():

    mimetype = 'application/json'
    result = {}

    action = request.args.get('action')
    static_home = '/Users/jinweihe/python-projects/diary/static'
    print(os.path.join(static_home,'third_party', 'ueditor', 'js', 'php', 'config.json'))

    try:
        with open(os.path.join(static_home,'third_party', 'ueditor', 'js', 'php', 'config.json')) as fp:
            try:
                CONFIG = json.loads(re.sub(r'\/\*.*\*\/', '', fp.read()))
            except:
                CONFIG = {}
    except IOError,e:
        print(e)

    if action == 'config':
        result = CONFIG

    elif action in ('uploadimage', 'uploadfile', 'uploadvideo'):
        # 图片、文件、视频上传
        if action == 'uploadimage':
            fieldName = CONFIG.get('imageFieldName')
            config = {
                "pathFormat": CONFIG['imagePathFormat'],
                "maxSize": CONFIG['imageMaxSize'],
                "allowFiles": CONFIG['imageAllowFiles']
            }
        elif action == 'uploadvideo':
            fieldName = CONFIG.get('videoFieldName')
            config = {
                "pathFormat": CONFIG['videoPathFormat'],
                "maxSize": CONFIG['videoMaxSize'],
                "allowFiles": CONFIG['videoAllowFiles']
            }
        else:
            fieldName = CONFIG.get('fileFieldName')
            config = {
                "pathFormat": CONFIG['filePathFormat'],
                "maxSize": CONFIG['fileMaxSize'],
                "allowFiles": CONFIG['fileAllowFiles']
            }
        if fieldName in request.files:
            field = request.files[fieldName]
            uploader = Uploader(field, config, static_home)
            result = uploader.getFileInfo()
        else:
            result['state'] = '上传接口出错'
    elif action in ('uploadscrawl'):
        # 涂鸦上传
        fieldName = CONFIG.get('scrawlFieldName')
        config = {
            "pathFormat": CONFIG.get('scrawlPathFormat'),
            "maxSize": CONFIG.get('scrawlMaxSize'),
            "allowFiles": CONFIG.get('scrawlAllowFiles'),
            "oriName": "scrawl.png"
        }
        if fieldName in request.form:
            field = request.form[fieldName]
            uploader = Uploader(field, config, static_home, 'base64')
            result = uploader.getFileInfo()
        else:
            result['state'] = '上传接口出错'
    elif action in ('catchimage'):
        config = {
            "pathFormat": CONFIG['catcherPathFormat'],
            "maxSize": CONFIG['catcherMaxSize'],
            "allowFiles": CONFIG['catcherAllowFiles'],
            "oriName": "remote.png"
        }
        fieldName = CONFIG['catcherFieldName']
        if fieldName in request.form:
            # 这里比较奇怪，远程抓图提交的表单名称不是这个
            source = []
        elif '%s[]' % fieldName in request.form:
            # 而是这个
            source = request.form.getlist('%s[]' % fieldName)
        _list = []
        for imgurl in source:
            uploader = Uploader(imgurl, config, static_home, 'remote')
            info = uploader.getFileInfo()
            _list.append({
                'state': info['state'],
                'url': info['url'],
                'original': info['original'],
                'source': imgurl,
            })
        result['state'] = 'SUCCESS' if len(_list) > 0 else 'ERROR'
        result['list'] = _list
    else:
        result['state'] = '请求地址出错'
    result = json.dumps(result)
    if 'callback' in request.args:
        callback = request.args.get('callback')
        if re.match(r'^[\w_]+$', callback):
            result = '%s(%s)' % (callback, result)
            mimetype = 'application/javascript'
        else:
            result = json.dumps({'state': 'callback参数不合法'})
    res = make_response(result)
    res.mimetype = mimetype
    res.headers['Access-Control-Allow-Origin'] = '*'
    res.headers['Access-Control-Allow-Headers'] = 'X-Requested-With,X_Requested_With'
    return res

app/views/profile.py
# coding=utf-8

import os
from flask import Blueprint, request, session, render_template, redirect, url_for, json, make_response, jsonify
from MongoDBDao import DiaryDao, UserDao, PersonalSignDao, DiaryStatisticDao
import sys

reload(sys)
sys.setdefaultencoding('utf8')

profile = Blueprint('profile', __name__)

default_page_size = 1000


@profile.route('/profile/list/<owner_id>')
def profile_list(owner_id):

    # 查询所有者
    owner = UserDao.find_user_by_user_id(owner_id)

    # 查询count
    # total_count = DiaryDao.find_diaries_count(owner_id)
    #
    # # total_pages
    # total_pages = 0
    # if total_count < default_page_size:
    #     total_pages = 1
    # elif total_count % default_page_size == 0:
    #     total_pages = total_count / default_page_size
    # else:
    #     total_pages = (total_count / default_page_size) + 1

    # 查询列表
    diaries = DiaryDao.find_diaries(owner_id, 1, default_page_size)

    return render_template('profile.html', user_id=owner_id, diaries=diaries, owner=owner, select_type='0')


@profile.route('/profile/choose_by_type/<owner_id>/<diary_type>')
def choose_by_type(owner_id, diary_type):
    # 查询所有者
    owner = UserDao.find_user_by_user_id(owner_id)

    # 查询列表
    diaries = DiaryDao.find_diaries_by_type(owner_id, diary_type, 1, default_page_size)
    return render_template('profile.html', user_id=owner_id, diaries=diaries, owner=owner, select_type=diary_type)


@profile.route('/profile/personal_sign/<owner_id>')
def get_personal_sign_content(owner_id):
    personal_sign_record = PersonalSignDao.find_personal_sign_by_user_id(owner_id)
    if personal_sign_record is None:
        return ''

    return personal_sign_record['sign_content']


@profile.route('/profile/hot_diaries/<owner_id>')
def get_hot_diaries(owner_id):

    try:
        hot_statistics = DiaryStatisticDao.find_hot_top(owner_id, 5)
    except Exception as err:
        print(err)

    data = []
    for hot_statistic in hot_statistics:
        tmp = {}
        #tmp['user_id'] = hot_statistic['user_id']
        tmp['diary_id'] = hot_statistic['diary_id']
        #tmp['view_number'] = hot_statistic['view_number']
        diary = DiaryDao.find_diary_by_id(int(hot_statistic['diary_id']))
        tmp['title'] = diary['title']
        data.append(tmp)

    json_str = json.dumps(data)
    print(json_str)
    return json_str

templates/index.html
{% extends "layout.html" %}
{% block css_files %}
<link rel="stylesheet"
      href="{{ url_for('static', filename='assets/css/app.css') }}">
{% endblock %}

{% block js_files %}

<script>
    function go_write_diary() {
        window.location.href='/go_write_diary/' + {{ user_id }};
    }
</script>

{% endblock %}

{% block body %}
<div class="am-cf am-padding">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">首页</strong> /
        <small>日记列表</small>
    </div>
</div>

<div class="am-g">
    <div class="am-u-sm-12 am-u-md-6">
        <div class="am-btn-toolbar">
            <div class="am-btn-group am-btn-group-xs">
                <button type="button" onclick="go_write_diary()" class="am-btn am-btn-default"><span class="am-icon-plus"></span> 写日记</button>
                <!--<button type="button" class="am-btn am-btn-default"><span class="am-icon-save"></span> 保存</button>
                <button type="button" class="am-btn am-btn-default"><span class="am-icon-archive"></span> 审核</button>
                <button type="button" class="am-btn am-btn-default"><span class="am-icon-trash-o"></span> 删除</button>-->
            </div>
        </div>
    </div>
    <div class="am-u-sm-12 am-u-md-3">
        <div class="am-form-group">
            <select data-am-selected="{btnSize: 'sm'}">
                <option value="option1">所有类别</option>
                <option value="option2">IT业界</option>
                <option value="option3">数码产品</option>
                <option value="option3">笔记本电脑</option>
                <option value="option3">平板电脑</option>
                <option value="option3">只能手机</option>
                <option value="option3">超极本</option>
            </select>
        </div>
    </div>
    <div class="am-u-sm-12 am-u-md-3">
        <div class="am-input-group am-input-group-sm">
            <input type="text" class="am-form-field">
          <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
        </div>
    </div>
</div>

<div class="am-g">
    <div class="am-u-sm-12">
        <form class="am-form">
            <table class="am-table am-table-striped am-table-hover table-main">
                <thead>
                <tr>
                    <th class="table-title">标题</th>
                    <th class="table-type">类别</th>
                    <th class="table-type">天气</th>
                    <th class="table-date am-hide-sm-only">时间</th>
                    <th class="table-set">操作</th>
                </tr>
                </thead>
                <tbody>
                {% for diary in diaries %}
                <tr>
                    <td><a href="/view_diary/{{ diary.id }}">{{ diary.title }}</a></td>
                    <td>{{ diary.type }}</td>
                    <td>{{ diary.weather }}</td>
                    <td class="am-hide-sm-only">{{ diary.date }}</td>
                    <td>
                        <div class="am-btn-toolbar">
                            <div class="am-btn-group am-btn-group-xs">
                                <button class="am-btn am-btn-default am-btn-xs am-text-secondary"><span
                                        class="am-icon-pencil-square-o"></span> 编辑
                                </button>
                                <!--<button class="am-btn am-btn-default am-btn-xs am-hide-sm-only"><span
                                        class="am-icon-copy"></span> 复制-->
                                </button>
                                <button class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only"><span
                                        class="am-icon-trash-o"></span> 删除
                                </button>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="am-cf">
                共 {{ count }} 条记录
                <div class="am-fr">
                    <ul class="am-pagination">
                        <li class="am-disabled"><a href="#">«</a></li>
                        <li class="am-active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">»</a></li>
                    </ul>
                </div>
            </div>
            <hr/>
            <p>注：.....</p>
        </form>
    </div>
</div>

{% endblock %}

templates/layout.html
<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>XM 日记</title>
    <meta name="description" content="这是XM Diary的我的页面">
    <meta name="keywords" content="mine">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='assets/i/favicon.png') }}">
    <link rel="apple-touch-icon-precomposed" href="{{ url_for('static', filename='assets/i/app-icon72x72@2x.png') }}">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>

    <link rel="stylesheet" href="{{ url_for('static',filename='assets/css/amazeui.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/admin.css') }}">

    {% block css_files %}{% endblock %}

</head>
<body>
<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器，我们暂不支持。 请 <a href="http://browsehappy.com/"
                                                                 target="_blank">升级浏览器</a>
    以获得更好的体验！</p>
<![endif]-->

<header class="am-topbar admin-header">
    <div class="am-topbar-brand">
        <strong>XM</strong>
        <small>日记</small>
    </div>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only"
            data-am-collapse="{target: '#topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span
            class="am-icon-bars"></span></button>

    <div class="am-collapse am-topbar-collapse" id="topbar-collapse">

        <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
            <li><a href="javascript:;"><span class="am-icon-envelope-o"></span> 收件箱 <span
                    class="am-badge am-badge-warning">5</span></a></li>
            <li class="am-dropdown" data-am-dropdown>
                <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
                    <span class="am-icon-users"></span> 管理员 <span class="am-icon-caret-down"></span>
                </a>
                <ul class="am-dropdown-content">
                    <li><a href="#"><span class="am-icon-user"></span> 资料</a></li>
                    <li><a href="#"><span class="am-icon-cog"></span> 设置</a></li>
                    <li><a href="{{ url_for('login.logout') }}"><span class="am-icon-power-off"></span> 退出</a></li>
                </ul>
            </li>
            <li class="am-hide-sm-only"><a href="javascript:;" id="admin-fullscreen"><span
                    class="am-icon-arrows-alt"></span> <span class="admin-fullText">开启全屏</span></a></li>
        </ul>
    </div>
</header>

<div class="am-cf admin-main">
    <!-- sidebar start -->
    <div class="admin-sidebar am-offcanvas" id="admin-offcanvas">
        <div class="am-offcanvas-bar admin-offcanvas-bar">
            <ul class="am-list admin-sidebar-list">
                <li><a href="/mine/list"><span class="am-icon-home"></span> 我的</a></li>
                <li><a href="/profile/list/{{ user_id }}"><span class="am-icon-file"></span> 个人主页</a></li>
                <li><a href="/mine/go_write_diary"><span class="am-icon-table"></span> 写日记</a></li>
                <li><a href="/mine/personal_sign/edit"><span class="am-icon-table"></span> 个性签名</a></li>
                <li><a href="{{ url_for('login.logout') }}"><span class="am-icon-sign-out"></span> 注销</a></li>
            </ul>

            <div class="am-panel am-panel-default admin-sidebar-panel">
                <div class="am-panel-bd">
                    <p><span class="am-icon-bookmark"></span> 公告</p>
                    <p>时光静好，与君语；细水流年，与君同。</p>
                </div>
            </div>

            <div class="am-panel am-panel-default admin-sidebar-panel">
                <div class="am-panel-bd">
                    <p><span class="am-icon-tag"></span> wiki</p>
                    <p>Welcome to XM Diary!</p>
                </div>
            </div>
        </div>
    </div>
    <!-- sidebar end -->

    <!-- content start -->
    <div class="admin-content">
        {% block body %}{% endblock %}
    </div>
    <!-- content end -->

</div>

<a href="#" class="am-show-sm-only admin-menu" data-am-offcanvas="{target: '#admin-offcanvas'}">
    <span class="am-icon-btn am-icon-th-list"></span>
</a>

<footer>
    <hr>
    <p class="am-padding-left">TODO 备案先不加</p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="{{ url_for('static', filename='assets/js/amazeui.ie8polyfill.min.js') }}"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
<!--<![endif]-->
<script src="{{ url_for('static', filename='assets/js/amazeui.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/app.js') }}"></script>

{% block js_files %}{% endblock %}

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>XM 日记</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />

  <link rel="alternate icon" type="image/png" href="{{ url_for('static', filename='assets/i/favicon.png') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/amazeui.min.css') }}"/>
  <style>
    .header {
      text-align: center;
    }
    .header h1 {
      font-size: 200%;
      color: #333;
      margin-top: 30px;
    }
    .header p {
      font-size: 14px;
    }
  </style>
</head>
<body>
<div class="header">
  <div class="am-g">
    <h1>XM 日记</h1>
    <p>我们要养成写日记的好习惯<br/>记录,吐槽,秀恩爱...</p>
  </div>
  <hr />
</div>
<div class="am-g">
  <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">
    <h3>登录</h3>
    <hr>
    <div class="am-btn-group">
      <a href="#" class="am-btn am-btn-secondary am-btn-sm"><i class="am-icon-github am-icon-sm"></i> Github</a>
      <a href="#" class="am-btn am-btn-success am-btn-sm"><i class="am-icon-google-plus-square am-icon-sm"></i> Google+</a>
      <a href="#" class="am-btn am-btn-primary am-btn-sm"><i class="am-icon-stack-overflow am-icon-sm"></i> stackOverflow</a>
    </div>
    <br>
    <br>

{% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
    <form method="post" action="{{ url_for('login.do_login') }}" class="am-form">
      <label for="username">邮箱:</label>
      <input type="text" name="username" id="username" value="">
      <br>
      <label for="password">密码:</label>
      <input type="password" name="password" id="password" value="">
      <br>
      <label for="remember-me">
        <input id="remember-me" type="checkbox">
        记住密码
      </label>
      <br />
      <div class="am-cf">
        <input type="submit" name="" value="登 录" class="am-btn am-btn-primary am-btn-sm am-fl">
        <input type="submit" name="" value="忘记密码 ^_^? " class="am-btn am-btn-default am-btn-sm am-fr">
      </div>
    </form>
    <hr>
    <p>今晚打老虎</p>
  </div>
</div>
</body>
</html>

templates/personal_sign.html
{% extends "layout.html" %}
{% block css_files %}
<link rel="stylesheet"
      href="{{ url_for('static', filename='assets/css/app.css') }}">
{% endblock %}

{% block js_files %}

<script type="text/javascript">
    function save_personal_sign() {
        $.post('/mine/personal_sign/save',{
                sign_content: $('#sign_content').val()
            }, function(data) {
                if (data == 'ok') {
                    window.location.href='/mine/list';
                } else {
                    alert(data);
                }
            });
    }

</script>

{% endblock %}

{% block body %}
<div class="am-cf am-padding">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">我的</strong> /
        <small>个性签名</small>
    </div>
</div>

<div class="am-g">
    <div class="am-u-sm-12 am-u-md-12">
        <div class="am-form-group">
            <label for="sign_content">签名内容:</label>
            <textarea class="" rows="5" id="sign_content"></textarea>
        </div>
    </div>

    <p><button onclick="save_personal_sign()" type="button" class="am-btn am-btn-primary">提交</button></p>

</div>



{% endblock %}

templates/profile.html
{% extends "profile_layout.html" %}
{% block css_files %}

{% endblock %}

{% block js_files %}

<script>

    $(function(){
        $('#diary_type [value="{{ select_type }}"]').attr('selected', 'selected');
    });

    function select_type() {
        var type = $('#diary_type').val();

        if (type == '0') {
            window.location.href='/profile/list/' + {{ owner.user_id }};
        } else {
            window.location.href='/profile/choose_by_type/' + {{ owner.user_id }} + '/' + type;
        }
    }
</script>

{% endblock %}

{% block body %}

<div class="am-cf am-padding">
    <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">{{ owner.nickname }}</strong> /
        <small>日记列表</small>
    </div>
</div>

<div class="am-g">

    <div class="am-u-sm-12 am-u-md-3">
        <div class="am-form-group">
            <select id="diary_type" onchange="select_type()" data-am-selected="{btnSize: 'sm'}">
                <option value="0">所有类别</option>
                <option value="1">抒发感情</option>
                <option value="2">吐槽</option>
                <option value="3">秀恩爱</option>
            </select>
        </div>
    </div>
    <div class="am-u-sm-12 am-u-md-3">
        <div class="am-input-group am-input-group-sm">
            <input type="text" class="am-form-field">
          <span class="am-input-group-btn">
            <button class="am-btn am-btn-default" type="button">搜索</button>
          </span>
        </div>
    </div>
</div>

<div class="am-g">
    <div class="am-u-sm-12">
        <form class="am-form">
            <table class="am-table am-table-striped am-table-hover table-main">
                <thead>
                <tr>
                    <th class="table-title">标题</th>
                    <th class="table-type">类别</th>
                    <th class="table-type">天气</th>
                    <th class="table-date am-hide-sm-only">时间</th>
                </tr>
                </thead>
                <tbody>
                {% for diary in diaries %}
                <tr>
                    <td><a href="/mine/view_diary/{{ diary.id }}">{{ diary.title }}</a></td>
                    <td>
                        {% if diary.type == '1' %}
                            抒发感情
                        {% elif diary.type=='2' %}
                            吐槽
                        {% elif diary.type=='3' %}
                            秀恩爱
                        {% else %}
                            {{ diary.type }}
                        {% endif %}
                    </td>
                    <td>
                        {% if diary.weather == '1' %}
                            晴
                        {% elif diary.weather=='2' %}
                            雨
                        {% elif diary.weather=='3' %}
                            阴天
                        {% else %}
                            {{ diary.weather }}
                        {% endif %}
                    </td>
                    <td class="am-hide-sm-only">{{ diary.date }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </form>
    </div>
</div>

{% endblock %}